#!/bin/bash
echo 'size of directories in MB'
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo 'you did not specify a directy, using pwd'
    DIR=$(pwd)
    find $DIR -maxdepth 1 -type d -exec du -sm \{\} \; 2>/dev/null | sort -nr
else
    find $1 -maxdepth 1 -type d -exec du -sm \{\} \; 2>/dev/null | sort -nr
fi
